.TH ph_id 3 "Oct 2002" "University of Illinois" "C Library Calls"
.SH NAME
ph_id, ph_external, ph_status \- miscellaneous functions for PH server connections
.SH SYNOPSIS
.B #include <phclient.h>
.P
.BI "int ph_id(PH *" ph ", char *" id ");"
.br
.BI "int ph_status(PH *" ph ", char ** " motd ");"
.br
.BI "int ph_external(PH *" ph ");"
.SH VERSION
This man page documents version 1.2 of \fBlibphclient\fP.
.SH DESCRIPTION
The \fBph_id\fP() function adds an entry to the PH server's logs
containing the text found in \fIid\fP.  This is intended to be used
for tracking PH usage.

The \fBph_status\fP() function retrieves the server's message of the
day.  The \fImotd\fP argument is set to point to a dynamicly-allocated
string containing the text returned by the server.  It is then the
calling application's responsibility to free this memory when it is
no longer needed.

The \fBph_external\fP() function tells the server to consider the 
session non-local, even if it originated from a host which would
normally be treated as local.
.SH RETURN VALUE
These functions return 0 on success.  On error, they return -1 and set
\fIerrno\fP.
.SH ERRORS
These functions may fail with any error from the functions
\fIread\fP() or \fIwrite\fP().
.SH SEE ALSO
.BR read (2),
.BR write (2),
.BR ph_open (3)
